num1=int(input("Enter num1:"))
num2=int(input("Enter num2:"))
print("The Sum:",num1+num2)
print("The Difference:",num1-num2)
print("The Product:",num1*num2)
print("The Quotient:",num1/num2)
print("The reminder:",num1%30)
print("The Exponent:",num1**2)
print("The Floor Division:",num1//30)