num1=int(input("Enter num1:"))
num2=int(input("Enter num2:"))
print("number1=",num1,"and number2=",num2)
print("Is number1 == number2",num1==num2)
print("Is number1 > number2",num1>num2)
print("Is number1 < number2",num1<num2)
print("Is number1 >= number2",num1>=num2)
print("Is number <= number2",num1<=num2)
print("Is number != number2",num1!=num2)